image: maven:3-jdk-8

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    - ./config.properties

build:
  stage: build
  script:
    - |
      printf "data.dir=
      ant.home=
      db.url=
      db.username=
      db.password=
      cluster.mode=disabled
      cluster.java.home=
      cluster.reservation.name=
      cluster.timeout=2
      forceLocalExecution=enabled
      parallelize=disabled
      mutant.coverage=enabled
      block.attacker=enabled
      tomcat.username=
      tomcat.password=
      tomcat.url=
      tomcat.path=" | tee config.properties
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test checkstyle:checkstyle
    - |
      file="";
      first=1;
      output="checkstyle-report.json"
      path="$(pwd)";
      echo "[" > "$output";
      tail -n +3 target/checkstyle-result.xml | while read p; do
        if echo "$p" | grep -q "<file name.*" ; then
          file=$(expr "$p" : '<file name=\"\(.*\)\".*' | sed 's@'"$path"'@@g' );
          echo "$file";
        fi
        if echo "$p" | grep -q "<error.*" ; then
          line="$(expr "$p" : '.*line=\"\([0-9]*\)\".*')";
          message="$(expr "$p" : '.*message=\"\(.*\)\" source.*' | sed -e 's/&apos;/`/g' -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&quot;/\\\"/g' -e 's/&amp;/\&/g')"
          checksum=$(echo "$file $line $message" | sha1sum | awk '{print $1}')
          if [ "$first" == 1 ] ; then
            echo "{ \"description\": \"$message\", \"fingerprint\": \"$checksum\", \"location\": { \"path\": \"$file\", \"lines\": { \"begin\": \"$line\" }}}" >> "$output";
            first=0;
          else
            echo ",{ \"description\": \"$message\", \"fingerprint\": \"$checksum\", \"location\": { \"path\": \"$file\", \"lines\": { \"begin\": \"$line\" }}}" >> "$output"
          fi
        fi
      done ;
      echo "]" >> "$output"
    - cat target/site/jacoco-ut/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    paths:
      - target/surefire-reports/
      - target/site/jacoco-ut/
      - checkstyle-report.json
    reports:
      codequality:
        - checkstyle-report.json
      junit:
        - target/surefire-reports/TEST-*.xml

