
stages:
  - trigger

draft-job:
  stage: trigger
  # TODO: Replace with something else (e.g. sth more up to date)
  image: everpeace/curl-jq
  variables:
    # We do not need the repository
    GIT_STRATEGY: none
  before_script:
    - 'export SOURCE=$(cat $TRIGGER_PAYLOAD | jq -r .object_attributes.source_branch)'
    - 'export PREVIOUS=$(cat $TRIGGER_PAYLOAD | jq -r .changes.title.previous)'
    - 'export CURRENT=$(cat $TRIGGER_PAYLOAD | jq -r .changes.title.current)'
    - 'export IID=$(cat $TRIGGER_PAYLOAD | jq -r .object_attributes.iid)'
    - 'export PROJECT_ID=$(cat $TRIGGER_PAYLOAD | jq -r .project.id)'
    - 'printf "%s\n" "$SOURCE"'
    - 'printf "%s\n" "$PREVIOUS"'
    - 'printf "%s\n" "$CURRENT"'
  script:
    - 'if [[ $PREVIOUS = Draft:* ]]; then echo "Pass. Previous title is draft"; else echo "Fail. Previous was not in Draft."; exit 0; fi'
    - 'if [[ $CURRENT = Draft:* ]];  then echo "Fail. Current is in draft."; exit 0; else echo "Pass. Current title is not in draft."; fi'
    - 'curl --request POST --header "PRIVATE-TOKEN: ${PROJECT_TOKEN}" "https://gitlab.infosun.fim.uni-passau.de/api/v4/projects/${PROJECT_ID}/merge_requests/{$IID}/pipelines" | jq -r .web_url;'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
  tags:
    - deploy
