UPDATE events
SET Event_Type = 'PLAYER_MUTANT_EQUIVALENT'
WHERE Game_ID IN (SELECT ID FROM games WHERE Mode = 'MELEE')
  AND Event_Type = 'DEFENDER_MUTANT_EQUIVALENT';
UPDATE events
SET Event_Type = 'PLAYER_MUTANT_CLAIMED_EQUIVALENT'
WHERE Game_ID IN (SELECT ID FROM games WHERE Mode = 'MELEE')
  AND Event_Type = 'DEFENDER_MUTANT_CLAIMED_EQUIVALENT';
UPDATE events
SET Event_Type = 'PLAYER_TEST_CREATED'
WHERE Game_ID IN (SELECT ID FROM games WHERE Mode = 'MELEE')
  AND Event_Type = 'DEFENDER_TEST_CREATED';
UPDATE events
SET Event_Type = 'PLAYER_MUTANT_CREATED'
WHERE Game_ID IN (SELECT ID FROM games WHERE Mode = 'MELEE')
  AND Event_Type = 'ATTACKER_MUTANT_CREATED';
UPDATE events
SET Event_Type = 'PLAYER_MUTANT_SURVIVED'
WHERE Game_ID IN (SELECT ID FROM games WHERE Mode = 'MELEE')
  AND Event_Type = 'ATTACKER_MUTANT_SURVIVED';
