INSERT INTO settings (name, type, STRING_VALUE, INT_VALUE, BOOL_VALUE) VALUES
    ('CONTACT_NOTICE', 'STRING_VALUE', '', NULL, NULL),
    ('TEACHER_APPLICATIONS_ENABLED', 'BOOL_VALUE', NULL, NULL, FALSE),
    ('TEACHER_APPLICATIONS_EMAIL', 'STRING_VALUE', '', NULL, NULL);

