version: '2'
services:
  db:
    build:
      context: ./backend
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}
    image: codedefenders-back:dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: defender
      MYSQL_PASSWORD: defender
      MYSQL_DATABASE: defender
    ports:
      - "3306"
    volumes:
      - dbvolume:/var/lib/mysql

  # Tomcat nodes. We do not expose directly their ports to the outside
  frontend:
    build:
      context: ./frontend
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}
    image: codedefenders-front:dev
    restart: always
    environment:
      CODEDEF_MANAGER_USERNAME: user
      CODEDEF_MANAGER_PASSWORD: password
      CODEDEF_MANAGER_ALLOWED_REMOTE_ADDR: ${ALLOWED_REMOTE_ADDR_REGEXP}
      CODEDEF_ADMIN_USERNAME: admin
      CODEDEF_ADMIN_PASSWORD: password
      CODEDEF_CFG_DB_URL: "jdbc:mysql://db:3306/defender"
      CODEDEF_CFG_DB_USERNAME: defender
      CODEDEF_CFG_DB_PASSWORD: defender
    links:
      - db
    volumes:
      - datavolume:/codedefenders/

  # Note that we build this one... Since we need to install the sticky-session module
  load-balancer:
    build: ./load-balancer
    image: codedefenders-lb:dev
    restart: always
    tty: true
    links:
      - frontend
    ports:
      - "80:80"

volumes:
    datavolume:
    dbvolume:
