version: '2'
services:
  database:
    image: "mariadb:10.5"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'YES'
      MYSQL_USER: codedefenders
      MYSQL_PASSWORD: codedefenders
      MYSQL_DATABASE: codedefenders
    ports:
      - "3306"
    volumes:
      - dbvolume:/var/lib/mysql
  codedefenders:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      CODEDEFENDERS_DATA_DIR: /srv/codedefenders
      CODEDEFENDERS_DB_HOST: database
      CODEDEFENDERS_DB_PASSWORD: codedefenders
      CODEDEFENDERS_ADMIN_USERNAME: admin
      CODEDEFENDERS_ADMIN_PASSWORD: admin
    ports:
      - "8080"
    links:
      - database
    volumes:
      - datavolume:/srv/codedefenders

volumes:
  datavolume:
  dbvolume:
