ALTER TABLE classes
MODIFY COLUMN `AssertionLibrary`
    ENUM ('JUNIT4', 'JUNIT5',
        'HAMCREST', 'JUNIT4_HAMCREST', 'JUNIT5_HAMCREST',
        'GOOGLE_TRUTH', 'JUNIT4_GOOGLE_TRUTH', 'JUNIT5_GOOGLE_TRUTH')
    NOT NULL DEFAULT 'JUNIT4_HAMCREST';
