
-- Incorrect datetime value: '0000-00-00 00:00:00' for columns 'Finish_Time', 'Start_Time'
ALTER TABLE games ALTER COLUMN Start_Time SET DEFAULT '1970-02-02 01:01:01', ALTER COLUMN Finish_Time SET DEFAULT '1970-02-02 01:01:01';
ALTER TABLE games ADD MaxAssertionsPerTest INT DEFAULT 2 NOT NULL;
ALTER TABLE games ADD MutantValidator ENUM('STRICT', 'MODERATE', 'RELAXED') DEFAULT 'STRICT' NOT NULL;
ALTER TABLE games ADD MarkUncovered BOOL DEFAULT FALSE  NOT NULL;
ALTER TABLE games ADD ChatEnabled BOOL DEFAULT TRUE  NULL;