<%--

    Copyright (C) 2016-2019 Code Defenders contributors

    This file is part of Code Defenders.

    Code Defenders is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or (at
    your option) any later version.

    Code Defenders is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Code Defenders. If not, see <http://www.gnu.org/licenses/>.

--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%--@elvariable id="testAccordion" type="org.codedefenders.beans.game.TestAccordionBean"--%>

<%--
    Displays an accordion of tables of tests, grouped by which of the CUT's methods they cover.

    The accordion is generated by the JSP, the tables in the accordion sections as well as popovers and models are
    generated through JavaScript.
--%>

<style>
    <%-- Prefix all classes with "ta-" to avoid conflicts.
    We probably want to extract some common CSS when we finally tackle the CSS issue. --%>

    /* Customization of Bootstrap 5 accordion style.
    ----------------------------------------------------------------------------- */

    #tests-accordion .accordion-button {
        padding: .6rem .8rem;
        background-color: rgba(0,0,0,.03);
    }

    /* Clear the box shadow from .accordion-button. This removes the blue outline when selecting a button, and the
       border between the header and content of accordion items when expanded. */
    #tests-accordion .accordion-button {
        box-shadow: none;
    }
    /* Add back the border between header and content of accordion items. */
    #tests-accordion .accordion-body {
        border-top: 1px solid rgba(0, 0, 0, .125);
    }
    /* Always display the chevron icon in black. */
    #tests-accordion .accordion-button:not(.collapsed)::after {
        /* Copied from Bootstrap 5. */
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23212529'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
    }

    /* Categories.
    ----------------------------------------------------------------------------- */

    #tests-accordion .accordion-button:not(.ta-covered) {
        color: #B0B0B0;
    }
    #tests-accordion .accordion-button.ta-covered {
        color: black;
    }

    /* Tables.
    ----------------------------------------------------------------------------- */

    #tests-accordion thead {
        display: none;
    }
    #tests-accordion .dataTables_scrollHead {
        display: none;
    }
    #tests-accordion td {
        vertical-align: middle;
    }
    #tests-accordion table {
        font-size: inherit;
    }
    #tests-accordion tr:last-child > td {
        border-bottom: none;
    }

    /* Inline elements.
    ----------------------------------------------------------------------------- */

    #tests-accordion .ta-column-name {
        color: #B0B0B0;
    }
    #tests-accordion .ta-covered-link,
    #tests-accordion .ta-killed-link,
    #tests-accordion .ta-smells-link {
        cursor: default;
    }
</style>

<div class="accordion" id="tests-accordion">
    <c:forEach items="${testAccordion.categories}" var="category">
        <div class="accordion-item">
            <h2 class="accordion-header" id="ta-heading-${category.id}">
                <%-- ${empty …} doesn't work with Set --%>
                <button class="${category.testIds.size() == 0 ? "" : "ta-covered"} accordion-button collapsed"
                        type="button" data-bs-toggle="collapse"
                        data-bs-target="#ta-collapse-${category.id}"
                        aria-controls="ta-collapse-${category.id}">
                    <%-- ${empty …} doesn't work with Set --%>
                    <c:if test="${!(category.testIds.size() == 0)}">
                        <span class="badge bg-defender me-2 ta-count">${category.testIds.size()}</span>
                    </c:if>
                    ${category.description}
                </button>
            </h2>
            <div class="accordion-collapse collapse"
                 id="ta-collapse-${category.id}"
                 data-bs-parent="#tests-accordion"
                 aria-expanded="false" aria-labelledby="ta-heading-${category.id}">
                <div class="accordion-body p-0">
                    <table id="ta-table-${category.id}" class="table table-sm"></table>
                </div>
            </div>
        </div>
    </c:forEach>
</div>

<script type="text/javascript" src="js/test_accordion.js"></script>

<script>
    /* Wrap in a function to avoid polluting the global scope. */
    (function () {
        const categories = JSON.parse('${testAccordion.categoriesAsJSON}');
        const tests = new Map(JSON.parse('${testAccordion.testsAsJSON}'));

        CodeDefenders.objects.test_accordion = new CodeDefenders.classes.TestAccordion(categories, tests);
    })();
</script>
